[package]
name = "kerby"
version = "0.1.0"
authors = ["Zer1t0 <Zer1t0@mail.com>"]
edition = "2018"

[dependencies]
red_asn1 = { path = "../red_asn1/red_asn1" }

ascii = "0.9.1"
chrono = "0.4"
failure = "0.1.5"
failure_derive = "0.1.5"
rand = "0.6.5"
md4 = "0.8"
rust-crypto = "0.2"
num = "0.2"
dns-lookup = "1.0"